### ISSUE TITLE
Use a .env file for usernames and passwords

### ISSUE THREAD

**Issue by Santhoshkumard11** [Santhoshkumard11/Private-Messaging-using-MQTT-HiveQT#2]
Load the **username and password** from an `.env ` file instead of hardcoding it in the python code.
Never hardcode password or usernames in the code - Best Practice.

**Comment by sighclone** [comment]
Hi! I'd like to solve this issue

**Comment by ThisIsMatin** [comment]
Hi @Santhoshkumard11 , if someone is not working on this issue, I can work on this :)

**Comment by sighclone** [comment]
I've potentially solved the issue, please see the PR(#3) and let me know
