### ISSUE TITLE
handle exceptions both while connecting to the HiveQT and sending message

### ISSUE THREAD

**Issue by Santhoshkumard11** [Santhoshkumard11/Private-Messaging-using-MQTT-HiveQT#7]
There is no handling of exception in the code which can cause the code to break when the username or password is wrong and if there is no internet connectivity
- handle exception while connecting in publisher
- handle exception while publishing a message to a topic

**Comment by umairkarel** [comment]
```python
try:
    client.username_pw_set(f'{config["username"]}', f'{config["password"]}')
except:
    print("username or password doesn't Exist.")
```

This is what we have to add right?

**Comment by Santhoshkumard11** [comment]
@umairkarel I'm afraid that's not the place where a connection is established.
Check this [line](https://github.com/Santhoshkumard11/Private-Messaging-using-MQTT-HiveQT/blob/e8514b357e18308f1e3f3e90e28ec1477974558c/publisher.py#L31)
